import type { SudoKuDataType } from '../../store/sudokuSlice';
import { rowsEnum, columnsEnum } from '@/components/constants';

export const gridStructures: SudoKuDataType = {
  [rowsEnum?.row_1]: {
    [columnsEnum?.column_1]: {
      group: 1,
      row: 1,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 1,
      row: 1,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 1,
      row: 1,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 2,
      row: 1,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 2,
      row: 1,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 2,
      row: 1,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 3,
      row: 1,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 3,
      row: 1,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 3,
      row: 1,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_2]: {
    [columnsEnum?.column_1]: {
      group: 1,
      row: 2,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 1,
      row: 2,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 1,
      row: 2,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 2,
      row: 2,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 2,
      row: 2,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 2,
      row: 2,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 3,
      row: 2,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 3,
      row: 2,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 3,
      row: 2,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_3]: {
    [columnsEnum?.column_1]: {
      group: 1,
      row: 3,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 1,
      row: 3,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 1,
      row: 3,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 2,
      row: 3,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 2,
      row: 3,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 2,
      row: 3,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 3,
      row: 3,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 3,
      row: 3,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 3,
      row: 3,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_4]: {
    [columnsEnum?.column_1]: {
      group: 4,
      row: 4,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 4,
      row: 4,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 4,
      row: 4,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 5,
      row: 4,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 5,
      row: 4,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 5,
      row: 4,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 6,
      row: 4,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 6,
      row: 4,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 6,
      row: 4,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_5]: {
    [columnsEnum?.column_1]: {
      group: 4,
      row: 5,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 4,
      row: 5,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 4,
      row: 5,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 5,
      row: 5,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 5,
      row: 5,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 5,
      row: 5,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 6,
      row: 5,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 6,
      row: 5,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 6,
      row: 5,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_6]: {
    [columnsEnum?.column_1]: {
      group: 4,
      row: 6,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 4,
      row: 6,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 4,
      row: 6,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 5,
      row: 6,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 5,
      row: 6,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 5,
      row: 6,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 6,
      row: 6,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 6,
      row: 6,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 6,
      row: 6,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_7]: {
    [columnsEnum?.column_1]: {
      group: 7,
      row: 7,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 7,
      row: 7,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 7,
      row: 7,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 8,
      row: 7,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 8,
      row: 7,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 8,
      row: 7,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 9,
      row: 7,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 9,
      row: 7,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 9,
      row: 7,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_8]: {
    [columnsEnum?.column_1]: {
      group: 7,
      row: 8,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 7,
      row: 8,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 7,
      row: 8,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 8,
      row: 8,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 8,
      row: 8,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 8,
      row: 8,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 9,
      row: 8,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 9,
      row: 8,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 9,
      row: 8,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
  [rowsEnum?.row_9]: {
    [columnsEnum?.column_1]: {
      group: 7,
      row: 9,
      column: 1,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_2]: {
      group: 7,
      row: 9,
      column: 2,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_3]: {
      group: 7,
      row: 9,
      column: 3,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_4]: {
      group: 8,
      row: 9,
      column: 4,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_5]: {
      group: 8,
      row: 9,
      column: 5,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_6]: {
      group: 8,
      row: 9,
      column: 6,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_7]: {
      group: 9,
      row: 9,
      column: 7,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_8]: {
      group: 9,
      row: 9,
      column: 8,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
    [columnsEnum?.column_9]: {
      group: 9,
      row: 9,
      column: 9,
      crossedValues: [],
      possibleValues: [],
      value: undefined,
    },
  },
};
